service: workshop-serverless-graphql
app: workshop-serverless-graphql

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline-sqs
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

# you can overwrite defaults here
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}

custom: 
  ingestStream: ingest-${self:provider.stage}
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: eu-west-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

functions:
  pull-data:
    handler: src/functions/pull-data.handler
    events:
      - schedule: rate(1 hour)
      - http:
          path: pull-data
          method: get
          cors: true
  ingest:
    handler: src/functions/ingest.handler
    events:
      - http:
          path: ingest
          method: post
          cors: true
  process:
    handler: src/functions/process.handler
    events:
      - sqs:
          queueName: IngestQueue
          arn:
            Fn::GetAtt:
              - IngestQueue
              - Arn
  expose:
    handler: src/functions/expose.handler
  graphql:
    handler: src/functions/graphql.handler
    events:
    - http:
        path: graphql
        method: post
        cors: true

resources:
  Resources:
    MyFourthQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: IngestQueue
