service: workshop-serverless-graphql
app: workshop-serverless-graphql

plugins: 
  - serverless-offline
  - serverless-webpack
  - serverless-offline-kinesis
  - serverless-scriptable-plugin
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x

# you can overwrite defaults here
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}

custom: 
  ingestStream: ingest-${self:provider.stage}
  serverless-offline-kinesis:
    apiVersion: '2013-12-02'
    endpoint: http://0.0.0.0:4567
    region: eu-west-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
    readInterval: 500
    scriptHooks:
      after:package:createDeploymentArtifacts: npm run create-stream

functions:
  pull-data:
    handler: src/functions/pull-data.handler
    events:
      - schedule: rate(1 hour)
      - http:
          path: pull-data
          method: get
          cors: true
  ingest:
    handler: src/functions/ingest.handler
    events:
      - http:
          path: ingest
          method: post
          cors: true
  process:
    handler: src/functions/process.handler
    events:
      - stream:
          type: kinesis
          arn: 
            Fn::GetAtt: [ IngestStream, Arn ]
          batchSize: 1
          startingPosition: LATEST
          enabled: true
  expose:
    handler: src/functions/expose.handler
  graphql:
    handler: src/functions/graphql.handler
    events:
    - http:
        path: graphql
        method: post
        cors: true

resources: 
  Resources:
    IngestStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${self:custom.ingestStream}
        ShardCount: 1
